import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "@/components/Navbar";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Wealth Manager",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.className}`}>
          <main className="container min-h-screen">
            <Navbar />
            <div className="mt-20">{children}</div>
          </main>
          <Toaster />

          {/* {"Footer is here"} */}
          <div className="footer section mx-auto bg-gray-600">
            <footer className="py-4 text-center font-bold text-blue-50">
              <p>© 2025 Wealth Manager </p>
              <p>Made with 💗 by Priyanshu Malaviya </p>
            </footer>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
