name: Setup Nextjs

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build-test-lint-typecheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
