name: Setup Nextjs

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build-test-lint-typecheck:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["18", "20"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Lint
        run: npm run lint

      - name: Build
        run: npx prisma generate && npm run build
